Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/bionic64"



config.vm.provider "virtualbox" do |vb|
vb.memory = 2048
vb.cpus = 1
vb.name = "client3"
end

config.vm.network "private_network", ip: "192.168.1.13"
config.vm.hostname = "client3"
config.vm.provision :shell, :path => "install.sh" 
end